
// Data models for the Reading Agent

export interface ChapterAnalysis {
  chapterTitle: string;
  summary: string;
  corePoints: string[];
  novelInsights: string[]; // "New" or noteworthy perspectives
  keyQuotes: string[]; // New: Original text excerpts
}

export interface CrossReference {
  mainIdea: string;
  similarBooks: Array<{
    bookTitle: string;
    explanation: string;
  }>;
  opposingBooks: Array<{
    bookTitle: string;
    explanation: string;
  }>;
}

export interface BookAnalysisResult {
  title: string;
  author?: string;
  introduction: string; // General introduction to the book content
  coverImageDescription?: string; // Short description to generate a placeholder style
  coverImageUrl?: string; // Base64 image generated by Imagen
  chapters: ChapterAnalysis[];
  crossReferences: CrossReference[];
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  text: string;
  timestamp: number;
}

export interface ReadBookLog {
  id: string;
  title: string;
  author: string;
  completedAt: number; // timestamp
  data: BookAnalysisResult; // Persist the full analysis to restore later
}

export interface ReadingStats {
  total: number;
  thisWeek: number;
  thisMonth: number;
  thisYear: number;
}

export enum InputMode {
  SEARCH = 'SEARCH',
  PDF = 'PDF'
}

export enum AppStatus {
  IDLE = 'IDLE',
  ANALYZING = 'ANALYZING',
  READY = 'READY',
  ERROR = 'ERROR'
}
